#!/usr/bin/env python3
"""Generate a Markdown review report for recent activity candidates."""

from __future__ import annotations

import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
ACTIVITY_DIR = ROOT / "data" / "activity"
REPORT_DIR = ROOT / "reports"

CANDIDATES_PATH = ACTIVITY_DIR / "candidates.json"
PUBLISHED_PATH = ACTIVITY_DIR / "published.json"
REJECTED_PATH = ACTIVITY_DIR / "rejected.json"


def load_json(path: Path, default: Any) -> Any:
    if not path.exists():
        return default
    text = path.read_text(encoding="utf-8").strip()
    if not text:
        return default
    return json.loads(text)


def main() -> int:
    candidates = load_json(CANDIDATES_PATH, [])
    published = load_json(PUBLISHED_PATH, [])
    rejected = load_json(REJECTED_PATH, [])

    by_actor = defaultdict(list)
    for item in candidates:
        by_actor[item.get("canonical_name") or item.get("actor_id") or "Unknown"].append(item)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        "# Recent activity candidate review",
        "",
        f"Generated: {now}",
        "",
        "## Summary",
        "",
        f"- Auto candidates: {len(candidates)}",
        f"- Published items: {len(published)}",
        f"- Rejected items: {len(rejected)}",
        "",
        "## Review policy",
        "",
        "- Candidates are generated by actor name/alias matching.",
        "- Name matching alone does not prove attribution.",
        "- Move confirmed items from `data/activity/candidates.json` to `data/activity/published.json` to show them on the public UI.",
        "- Move false positives to `data/activity/rejected.json` to suppress them in future runs.",
        "",
        "## Candidates by actor",
        "",
    ]

    if not candidates:
        lines.append("- No candidates.")
    else:
        for actor_name in sorted(by_actor):
            lines.append(f"### {actor_name}")
            lines.append("")
            for item in sorted(by_actor[actor_name], key=lambda row: row.get("published_date") or "", reverse=True):
                matched = ", ".join(item.get("matched_names") or [])
                date = item.get("published_date") or "date unknown"
                publisher = item.get("publisher") or "publisher unknown"
                title = item.get("title") or "(no title)"
                url = item.get("url") or ""
                summary = item.get("summary") or ""

                lines.append(f"- **{date} / {publisher}**")
                lines.append(f"  - Title: {title}")
                lines.append(f"  - URL: {url}")
                lines.append(f"  - Matched names: {matched}")
                if summary:
                    lines.append(f"  - Summary: {summary[:250]}")
                lines.append("")

    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORT_DIR / "latest-activity-candidates.md"
    report_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

    print(f"Wrote {report_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
